# Generated by Django 6.0.5 on 2026-05-23 13:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ISBNコード')),
                ('title', models.CharField(max_length=255, verbose_name='書名')),
                ('author', models.CharField(max_length=255, verbose_name='著者名')),
                ('price', models.IntegerField(verbose_name='価格（円）')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('category', models.CharField(choices=[('IT・技術', 'IT・技術'), ('文学', '文学'), ('ビジネス', 'ビジネス'), ('サイエンス', 'サイエンス'), ('教育', '教育'), ('その他', 'その他')], default='IT・技術', max_length=50, verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '書籍目録',
                'verbose_name_plural': '書籍目録一覧',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='利用者カード番号')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('address', models.CharField(max_length=255, verbose_name='現住所')),
                ('phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('status', models.CharField(choices=[('Active', '適格（有効）'), ('Suspended', '不適格（停止中）')], default='Active', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': '登録利用者',
                'verbose_name_plural': '登録利用者一覧',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('copy_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='蔵書ID')),
                ('status', models.CharField(choices=[('Available', '貸出可能'), ('Loaned', '貸出中'), ('Lost', '紛失'), ('Maintenance', 'メンテナンス中')], default='Available', max_length=20, verbose_name='状態')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='library_app.book', verbose_name='書籍')),
            ],
            options={
                'verbose_name': '蔵書コピー',
                'verbose_name_plural': '蔵書コピー一覧',
                'ordering': ['copy_id'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=10, unique=True, verbose_name='貸出ID')),
                ('loan_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='貸出日')),
                ('due_date', models.DateTimeField(verbose_name='返却期限日')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='実際の返却日')),
                ('status', models.CharField(choices=[('Active', '貸出中'), ('Returned', '返却済み'), ('Overdue', '返却遅延')], default='Active', max_length=20, verbose_name='状況')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library_app.bookcopy', verbose_name='蔵書コピー')),
                ('librarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当司書')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library_app.libraryuser', verbose_name='利用者')),
            ],
            options={
                'verbose_name': '貸出台帳',
                'verbose_name_plural': '貸出台帳一覧',
                'ordering': ['-loan_date'],
            },
        ),
    ]
